name: Asterius

on:
  - push
  - pull_request

jobs:

  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          podman run \
            --network host \
            --pull always \
            --rm \
            --workdir $(pwd) \
            --volume $(pwd):$(pwd) \
            debian:sid-slim \
            ./asterius_build.sh

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-asterius
          path: dist
