name: asterius

on:
  - push
  - pull_request

jobs:

  nix:
    name: nix-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: setup-nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/1916bd87173c3af6efa077da53180a16f3697139.tar.gz

      - name: build
        run: |
          nix-build -A dist .
          cp $(realpath result-dist) wasi-sdk.tar.zst

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.os }}
          path: wasi-sdk.tar.zst
